### ISSUE TITLE
Who developed Go?

### ISSUE THREAD

**Issue by ledongthuc** [pedrobertao/golang-interview-prep#1]
Hi, First, thanks for sharing.
And I want to double-check the sentence of
```Go, also known as Golang, is an open-source programming language developed by Google.```
As I understand, the Go is developed at Google, by [Robert Griesemer](https://en.wikipedia.org/wiki/Robert_Griesemer), [Rob Pike](https://en.wikipedia.org/wiki/Rob_Pike), and [Ken Thompson](https://en.wikipedia.org/wiki/Ken_Thompson). It's not developed by Google as my understanding, although it's started to use in Google.

**Comment by pedrobertao** [comment]
@ledongthuc  Hello, thanks for your feedback but according to their [website](https://developers.google.com/learn/topics/go), I quote:

> Go is an open source, strongly typed, compiled language written to build concurrent and scalable software. The language was invented at Google by Rob Pike, Ken Thomson, and Robert Griesemer. Go is designed for simple, reliable, and efficient software.

**Comment by ledongthuc** [comment]
yes, that's what I mean. It was developed at Google by Rob, Ken, and Robert. it was not developed by Google.
The `term developed by Google` is confusing and easier to understand Google invented it. But actually, Rob, Ken and Robert developed it when they were working at Google.

**Comment by pedrobertao** [comment]
Ok, now I get your point. I will mark as an issue. Will update soon

**Comment by pedrobertao** [comment]
https://github.com/pedrobertao/golang-interview-prep/commit/ff6379608abab683b9e5e45d9b7683bdccf42219
